GET http://localhost:3000/users/

###


POST http://localhost:3000/register
Content-Type: application/json

{   
    "name":"SanjeevGoud",
    "username":"Sanjeev12345",
    "password": "Sanjeev@4567",
    "gender": "Male",
    "location":"hyderabads"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Sanjeev123",
  "password": "Sanjeev@456"
}

###

PUT http://localhost:3000/change-password/

Content-Type: application/json

{
  "username": "Sanjeev123",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}